name: Collect Test Runs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  collect_tests_integration_org:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: schedule-test-runs.yml
        workflow_conclusion: success
        name: integration_test_run_id
        name_is_regexp: true

    - name: print contents
      run: |
        cd integration_test_run_id 
        cat integration_test_run_id.txt
        