name: Collect Test Runs

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  collect_tests_integration_org:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
        
    - name: Display structure of downloaded files
      run: ls -R
    