name: Run all tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  midnight_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: "14"

    - name: "Install Salesforce CLI"
      run: |
        npm install @salesforce/cli --location=global
        nodeInstallPath=$(npm config get prefix)
        echo "$nodeInstallPath/bin" >> $GITHUB_PATH
        sf --version
    
    - name: "Populate auth file with SFDX_URL secret"
      shell: bash
      run: |
        echo ${{ secrets.SFDX_INTEGRATION_URL}} > ./SFDX_INTEGRATION_URL.txt

    # Authenticate to org using the URL stored in the text file
    - name: "Authenticate to  Org"
      run: sfdx auth:sfdxurl:store -f ./SFDX_INTEGRATION_URL.txt -s -a integration

    - name: "Run all tests"
      run: |
        sfdx apex run test --test-level RunLocalTests --result-format human --output-dir output
        pwd
        ls
        

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: output/test-run-id.txt
      
