name: Midnight GMT Workflow

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  midnight_job:
    runs-on: ubuntu-latest

    steps:
      - name: Echo a message
        run: echo "This workflow runs at 12 midnight GMT"
